### ISSUE TITLE
Negative depth values being calculated in Impacts (L2) analysis

### ISSUE THREAD

**Issue by blhumphreys** [NRCan/CanFlood#90]
Hi, 

I am running a CanFlood model using building footprint polygons that are partially inundated when overlaid with water surface elevation rasters that have been outputted from a 2D model. The partial inundation is occurring partly because of low flood depths, and partly because of the DEM surface being uneven at the building footprints (interpolated from ground points surrounding the building).

I am noticing that this leads CanFlood to interpret the water surface as being below the DEM (regardless of the global sampling type), and therefore calculating the depths as negative values when running the Impacts L2 analysis. 

Is there a workaround for this that doesn't involve modifying the input DEM (i.e. assigning the min DEM elevation within a building footprint to the entire area)? 

Cheers,

Ben

**Comment by cefect** [comment]
Hi Ben, I'm not sure I understand the situation on the inputs... can you send a minimum working example (or at least a screen shot). Are you using a depths or a WSE raster?

**Comment by blhumphreys** [comment]
Hi Seth,

Thanks for the quick response. I am using WSE rasters. 

The below screenshot shows a partially inundated building footprint polygon, with the WSE raster overlaid on the DEM hillshade (with increased z factor to show areas of interpolation). The depth value being shown in the Impacts (L2) output is -0.03m, despite the 2D model results showing that there should be a positive depth. This leads to the damages being calculated as $0, as the lowest ground elevation assigned to the vulnerability curves is 0m.

Please let me know if you need more information.

Ben

![image](https://github.com/NRCan/CanFlood/assets/100965696/1c82d4d5-fb58-4dbf-8ed6-f832f40240a2)

**Comment by cefect** [comment]
Hi Ben,
Without seeing your model files, my guess is the DEM value is either being sampled at the centroid or the mean over the building... which is greater than the WSE at the edges (check your elevations file). A quick fix would be to use the minimum sampling statistic instead when running the elevations (I think these settings are controlled on the raster sampling tab). For problematic cases like this it is sometimes easier just to move the building slightly. Ideally, you would set the building heights as absolute (rather than relative to the DEM) but this requires you to calculate the building elevations somehow. Hope this helps,

**Comment by blhumphreys** [comment]
Hi Seth,

Thanks for the suggestions. I was able to solve the problem by assigning absolute DEM values to the buildings (using min DEM values at building footprints), then sampling max WSE in CanFlood.

Cheers,

Ben

**Comment by cefect** [comment]
Awesome!
